[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NIXPACKS_NO_CACHE = "1"
SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL = "False"
