# Render.com deployment configuration
# This file tells Render how to deploy your Flask app

services:
  - type: web
    name: sign-language-detector
    env: python
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
